# Library import

In [37]:
# Standard library imports (general utilities)
import os            # File and path operations
from typing import Optional, Dict, List, Tuple  # Type hints for readability

# Third‑party libraries (data science stack)
import numpy as np   # Numerical computing
import pandas as pd  # Data analysis and tabular processing
import matplotlib.pyplot as plt  # Plotting (will use for EDA visuals)

# Display options for clarity during EDA
pd.set_option("display.max_columns", 120)   # Show more columns in tables
pd.set_option("display.width", 160)         # Wider console width for tables

#### File path definition

In [38]:
# Base folder where raw data is stored
DATA_DIR = "./data/raw"

# Dictionary with key = dataset name, value = path to CSV
FILES = {"train_operational_readouts_csv": os.path.join(DATA_DIR, "train_operational_readouts.csv"), 
         "validation_operational_readouts": os.path.join(DATA_DIR, "validation_operational_readouts.csv"), 
         "test_operational_readouts": os.path.join(DATA_DIR, "test_operational_readouts.csv"), 
         "train_specifications": os.path.join(DATA_DIR, "train_specifications.csv"), 
         "validation_specifications": os.path.join(DATA_DIR, "validation_specifications.csv"), 
         "test_specifications": os.path.join(DATA_DIR, "test_specifications.csv"), 
         "train_tte": os.path.join(DATA_DIR, "train_tte.csv"), 
         "validation_labels": os.path.join(DATA_DIR, "validation_labels.csv"), 
         "test_labels": os.path.join(DATA_DIR, "test_labels.csv")}

for name, path in FILES.items(): # Quick check: print all paths
    print(f"{name:35} -> {path}")

train_operational_readouts_csv      -> ./data/raw\train_operational_readouts.csv
validation_operational_readouts     -> ./data/raw\validation_operational_readouts.csv
test_operational_readouts           -> ./data/raw\test_operational_readouts.csv
train_specifications                -> ./data/raw\train_specifications.csv
validation_specifications           -> ./data/raw\validation_specifications.csv
test_specifications                 -> ./data/raw\test_specifications.csv
train_tte                           -> ./data/raw\train_tte.csv
validation_labels                   -> ./data/raw\validation_labels.csv
test_labels                         -> ./data/raw\test_labels.csv

### Save csv files loader

In [39]:
def safe_read_csv(path: str, nrows: int | None = None) -> pd.DataFrame | None:
#  Safely reads a CSV. Returns None if the file does not exist or cannot be read.
    if not os.path.exists(path):
        print(f"[safe_read_csv] File does not exist: {path}")
        return None
    
    try:
        return pd.read_csv(path, low_memory=False, nrows=nrows)
    except Exception as exc:
        print(f"[safe_read_csv] Error reading {path}: {exc}")
        return None

#### Train_operational_readouts stats and EDA

In [40]:
DATA_DIR = "../data/raw" # Path to local file
train_ops_path = os.path.join(DATA_DIR, "train_operational_readouts.csv")
train_ops_df = safe_read_csv(train_ops_path, nrows=50_000) # Load a manageable sample (50k rows)

In [41]:
train_ops_df.shape

(50000, 107)

In [54]:
train_ops_df.head(206)

,vehicle_id,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35
0,0,11.2,167985.0,10787.0,7413813.0,2296.0,4110.0,1296420.0,1628265.0,630345.0,1269525.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1435083.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8036751.0,0.0,1227.0,555.0,463.0,925.0,468.0,225.0,535.0,516.0,492.0,729.0,66.0,97056.0,2690052.0,2945268.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,858410.0,203.676778,111.911500,147.265389,200.479944,230.306278,277.722417,315.748806,372.164528,864.246250,920.881111,637.901639,744.618944,880.866889,1272.323972,1847.623667,940.785694,2.900083,0.208444,0.056417,0.058444,446956.0,411420.0,203024.0,26636.0,29156.0,7616.0,449537.0,233352.0,139920.0,12648.0,2813.0,224.0,53161.0,178881.0,138250.0,13328.0,3581.0,88.0,16361.0,131601.0,116541.0,13506.0,2856.0,48.0,6337.0,105412.0,95728.0,15609.0,1984.0,8.0,784.0,150228.0,261904.0,93172.0,17874.0,452.0
1,0,11.4,167985.0,10787.0,7413813.0,2296.0,4111.0,1302855.0,1628265.0,630345.0,1269526.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1440661.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8040811.0,0.0,1230.0,558.0,463.0,925.0,469.0,226.0,535.0,516.0,493.0,729.0,66.0,97056.0,2693100.0,2947368.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,860571.0,204.256750,112.924250,147.265389,201.479944,230.306278,277.722417,315.748806,372.164528,864.246250,920.881111,637.901639,745.618944,880.866889,1272.323972,1847.623667,940.785694,2.900083,0.208444,0.056417,0.058444,446964.0,411420.0,203027.0,26638.0,29157.0,7616.0,451193.0,233354.0,139920.0,12649.0,2813.0,224.0,53210.0,178883.0,138252.0,13328.0,3582.0,88.0,16368.0,131601.0,116542.0,13507.0,2856.0,48.0,6339.0,105413.0,95729.0,15610.0,1984.0,8.0,784.0,150228.0,261905.0,93172.0,17874.0,452.0
2,0,19.6,331635.0,14525.0,13683604.0,2600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1787736.0,1133132.0,598351.0,1167062.0,12314224.0,460240.0,3887.0,0.0,0.0,0.0,12777022.0,0.0,2136.0,954.0,850.0,1420.0,722.0,412.0,880.0,666.0,586.0,1143.0,162.0,181632.0,4249020.0,4630440.0,1539133.0,1421172.0,1039764.0,749472.0,740724.0,995796.0,574045.0,1379191.0,321.671972,157.312500,193.792833,263.577611,310.711861,366.149250,415.642472,484.391167,1146.111611,1286.536333,900.062917,1123.232556,1449.545611,2140.037472,5046.748278,1151.010139,3.320194,0.218806,0.056778,0.058444,756665.0,647348.0,286811.0,30967.0,31213.0,7745.0,633790.0,423395.0,271940.0,16190.0,3573.0,232.0,75038.0,352791.0,327992.0,17325.0,4451.0,92.0,24028.0,234737.0,216619.0,17000.0,3476.0,48.0,12055.0,167693.0,142900.0,19263.0,2441.0,12.0,1420.0,204832.0,313485.0,106464.0,19306.0,452.0
3,0,20.2,354975.0,15015.0,14540449.0,2616.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1824409.0,1166074.0,634595.0,1233908.0,13275730.0,466753.0,3887.0,0.0,0.0,0.0,13612083.0,0.0,2218.0,1014.0,892.0,1471.0,749.0,425.0,901.0,702.0,589.0,1197.0,174.0,193728.0,4462548.0,4988028.0,1696022.0,1565484.0,1112544.0,789228.0,774588.0,1015104.0,576901.0,1428606.0,331.479028,162.731639,198.104472,269.712889,320.087333,377.478667,425.901361,495.749583,1173.882583,1323.460972,923.099361,1161.893139,1501.973944,2208.782833,5587.856667,1160.593833,3.336417,0.218806,0.056778,0.058444,812577.0,686860.0,302955.0,31927.0,31488.0,7749.0,651902.0,478279.0,292109.0,16755.0,3753.0,232.0,77118.0,394083.0,359060.0,17941.0,4573.0,92.0,25164.0,253706.0,232912.0,17583.0,3573.0,48.0,13199.0,176596.0,150565.0,19832.0,2522.0,12.0,1444.0,211688.0,318901.0,107745.0,19406.0,453.0
4,0,21.0,365550.0,15295.0,14966985.0,2720.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1873614.0,1176071.0,639587.0,1266369.0,13758524.0,474047.0,3887.0,0.0,0.0,0.0,14041353.0,0.0,2272.0,1038.0,910.0,1519.0,773.0,440.0,946.0,727.0,599.0,1233.0,178.0,203568.0,4621885.0,5107368.0,1758350.0,1633717.0,1159656.0,820368.0,792996.0,1030644.0,587234.0,1460547.0,339.563444,166.705583,202.430194,275.669056,327.877944,385.460472,435.321167,506.110639,1201.040833,1351.811444,944.133250,1192.740333,1544.355778,2307.900278,5738.170167,1182.611833,3.367250,0.218806,0.056778,0.058444,843929.0,710424.0,314292.0,32585.0,31896.0,7773.0,665154.0,488271.0,300083.0,17265.0,3998.0,232.0,79222.0,411299.0,371612.0,18614.0,4681.0,92.0,25736.0,268834.0,242477.0,18108.0,3641.0,52.0,13400.0,183724.0,155913.0,20573.0,2562.0,12.0,1445.0,213956.0,323997.0,109514.0,19535.0,454.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,2,253.6,5056005.0,270611.0,210665160.0,55677.0,10415.0,8194848.0,68911625.0,42181461.0,59091453.0,190900765.0,5375557.0,3350.0,0.0,0.0,593.0,14297495.0,36889678.0,22436306.0,32780425.0,220081463.0,3840114.0,0.0,0.0,0.0,0.0,241706136.0,0.0,30090.0,22612.0,29158.0,26396.0,9233.0,4537.0,9876.0,21933.0,2907.0,10849.0,3474.0,4922822.0,93600880.0,102003965.0,35946593.0,26682616.0,15116920.0,10040428.0,6855800.0,6197564.0,3548258.0,31351743.0,5252.545361,1679.535444,2163.595556,3088.284778,3748.318472,4603.052806,5120.489306,5757.896500,11529.062389,12108.439194,7783.334417,11256.590472,13044.143667,14052.736778,39344.381389,57751.991611,97.628694,3.510806,0.108389,0.065806,25885002.0,15515869.0,7639545.0,748373.0,258101.0,13788.0,6562584.0,6752785.0,8198523.0,346248.0,73785.0,1462.0,709864.0,4732614.0,8940123.0,259505.0,70429.0,1811.0,360301.0,2965236.0,4192458.0,191288.0,28556.0,518.0,139771.0,1732204.0,2171049.0,144676.0,22440.0,245.0,16034.0,1081028.0,1518111.0,308010.0,55989.0,789.0
202,2,264.4,5283300.0,277436.0,219726674.0,59669.0,10415.0,8493124.0,71569820.0,43832241.0,62227758.0,201047680.0,5574367.0,3350.0,0.0,0.0,943.0,14677212.0,37995055.0,23771874.0,34018844.0,231716126.0,3952161.0,0.0,0.0,0.0,0.0,253277216.0,0.0,31107.0,23194.0,30040.0,27303.0,9491.0,4759.0,10167.0,22461.0,3114.0,11332.0,3636.0,5174570.0,97452737.0,107646449.0,37986401.0,27837412.0,15783136.0,10464700.0,7129256.0,6392876.0,3638546.0,33311498.0,5572.707083,1734.491167,2233.666722,3187.021472,3879.535667,4763.801417,5315.167639,5972.096556,12003.918167,12656.368167,8137.348361,11691.934611,13527.370167,14573.049917,40162.941917,61212.138167,109.734750,3.764806,0.115806,0.065806,27509778.0,16190153.0,7985630.0,774413.0,264305.0,13942.0,6856652.0,7013474.0,8568315.0,357292.0,75313.0,1483.0,735140.0,4917675.0,9344171.0,267429.0,71702.0,1835.0,373777.0,3093072.0,4383930.0,197494.0,29141.0,518.0,146812.0,1811325.0,2266646.0,148892.0,22833.0,246.0,16911.0,1122744.0,1568919.0,313442.0,56323.0,789.0
203,2,266.4,5352210.0,279410.0,222421014.0,60845.0,10415.0,8525344.0,72038316.0,44206551.0,63008643.0,204059335.0,5664307.0,3350.0,0.0,0.0,1041.0,14748270.0,38204602.0,24019512.0,34288815.0,235066967.0,3992058.0,0.0,0.0,0.0,0.0,256343376.0,0.0,31398.0,23377.0,30358.0,27510.0,9575.0,4825.0,10282.0,22623.0,3183.0,11488.0,3684.0,5235566.0,98482277.0,108904625.0,38595953.0,28209364.0,15987136.0,10600240.0,7221644.0,6459644.0,3676082.0,33700823.0,5639.000806,1751.464361,2254.033111,3216.120361,3919.041056,4812.787500,5373.330056,6038.499028,12145.729083,12806.448000,8240.397056,11819.315694,13676.795806,14752.255500,40395.817000,62336.034972,112.495222,3.856944,0.115806,0.065806,27834307.0,16381253.0,8093334.0,781205.0,265881.0,13954.0,6938468.0,7084715.0,8684667.0,360453.0,75741.0,1483.0,742425.0,4967727.0,9472131.0,270138.0,72195.0,1835.0,378021.0,3130156.0,4443641.0,199814.0,29373.0,518.0,148672.0,1836378.0,2299879.0,150465.0,22966.0,246.0,17151.0,1134264.0,1585576.0,315110.0,56443.0,789.0
204,2,281.0,5648790.0,289371.0,233978571.0,68717.0,10415.0,9137870.0,74655621.0,45991626.0,65888583.0,215614075.0,5813857.0,3351.0,0.0,0.0,1615.0,15595949.0,39535581.0,24776970.0,35602881.0,247741500.0,4105379.0,0.0,0.0,0.0,0.0,268811996.0,0.0,32604.0,24271.0,31582.0,28392.0,9947.0,4990.0,10612.0,23437.0,3348.0,12076.0,3888.0,5514003.0,102778469.0,113214569.0,41164361.0,29912920.0,16933276.0,11216188.0,7651796.0,6792896.0,3921746.0,35001073.0,5884.212306,1824.544139,2345.898528,3347.191333,4084.983472,5034.092444,5654.534778,6331.081556,12744.702194,13486.259917,8700.091667,12485.053167,14442.414167,15692.169083,41570.264778,67290.974528,122.907639,4.581583,0.148417,0.066139,28726045.0,17168793.0,8501567.0,809705.0,271977.0,14103.0,7427893.0,7434832.0,9177568.0,374729.0,77737.0,1495.0,778581.0,5218923.0,10030540.0,281299.0,73925.0,1839.0,394986.0,3305181.0,4706445.0,209658.0,30394.0,518.0,156558.0,1947430.0,2448559.0,158719.0,23655.0,246.0,18151.0,1193941.0,1680728.0,328910.0,57511.0,793.0
205,3,0.2,1530.0,28.0,111133.0,0.0,0.0,178155.0,137220.0,26400.0,855.0,0.0,0.0,0.0,0.0,0.0,28.0,189423.0,63544.0,24740.0,24661.0,3003.0,0.0,0.0,0.0,0.0,0.0,221550.0,0.0,390.0,117.0,54.0,96.0,48.0,21.0,36.0,12.0,12.0,3.0,0.0,2448.0,184776.0,80341.0,8916.0,1812.0,996.0,300.0,1296.0,264.0,732.0,65625.0,17.751861,5.129250,3.700000,3.975444,4.070389,3.194389,2.690194,2.387194,5.103750,5.238472,2.085389,2.531306,2.075083,1.738333,3.409556,3.046417,0.000000,0.000000,0.000000,0.000000,5404.0,14440.0,1577.0,244.0,40.0,0.0,49805.0,10532.0,3197.0,300.0,68.0,8.0,3192.0,2257.0,696.0,84.0,20.0,4.0,472.0,386.0,112.0,120.0,20.0,0.0,64.0,108.0,52.0,8.0,24.0,8.0,0.0,4.0,221.0,40.0,296.0,165.0

In [ ]:
train_tte_path = os.path.join(DATA_DIR, "train_tte.csv")
train_tte_df = safe_read_csv(train_tte_path)

In [48]:
train_tte_df.head(100)

    vehicle_id  length_of_study_time_step  in_study_repair
0            0                      510.0                0
1            2                      281.8                0
2            3                      293.4                0
3            4                      210.0                0
4            5                      360.4                0
..         ...                        ...              ...
95         132                      208.4                0
96         134                      351.8                1
97         135                      490.0                0
98         136                      303.4                0
99         138                      254.4                0

[100 rows x 3 columns]

In [ ]:
train_ops_df.dtypes.value_counts()

float64    106
int64        1
Name: count, dtype: int64

> 106 float64 values are operational values (masked sensors or histograms)

In [ ]:

nan_percentage = (train_ops_df.isna().mean() * 100).sort_values(ascending=False)  # Missing values (top 10 columns with most NA)
print("\nMissing values (%):")
print(nan_percentage.head(100))

Missing values (%):
167_2    1.224
167_3    1.224
167_0    1.224
167_4    1.224
167_1    1.224
         ...
272_8    0.032
272_0    0.032
272_1    0.032
272_4    0.032
272_5    0.032
Length: 100, dtype: float64

In [ ]:
if "vehicle_id" in train_ops_df.columns and "time_step" in train_ops_df.columns:
    print("\nUnique vehicles:", train_ops_df["vehicle_id"].nunique())
    print("Min time_step:", train_ops_df["time_step"].min())
    print("Max time_step:", train_ops_df["time_step"].max())

Unique vehicles: 668
Min time_step: 0.0
Max time_step: 507.4

 - Each row = vehicle snapshot.
  - 2 types of features:
        Accumulative counters (increases value according to time_step).
        Bins Histograms (capture a variable distribution).
- NaN values, do not imply error, represent no data registered on that bin.
→ Can be speccificly replaced with a imputation plan (can be 0).

- Different scales (0.05 vs milions).
→ Its neccesary to use scalers or proportional converters to avoid modeling errors.